[build]
  command = "npm run build"
  publish = "build"

# Redirige todas las rutas de SPA
[[redirects]]
  from = "/gestion/*"
  to = "/gestion/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
